version: '3.8'

services:
  ktor-chat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: "mongodb+srv://tejas:22111287%40Tm@ktor-chat-app-backend-d.oaqrxzr.mongodb.net/?retryWrites=true&w=majority&appName=Ktor-chat-app-backend-db"
